CREATE TABLE UNIVERSITA (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  nome VARCHAR(250) NOT NULL,
  citta VARCHAR(250) NOT NULL
);

CREATE TABLE STUDENTE (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  id_universita INT ,
  nome VARCHAR(250) NOT NULL,
  cognome VARCHAR(250) NOT NULL,
  matricola VARCHAR(250) NOT NULL
);